### ISSUE TITLE
Textbox for aistream:key

### ISSUE THREAD

**Issue by mirekholec** [AlexBulankou/ai-stream#2]
Hi Alex, great work. **I recommend to change the ai:stream key Textbox from text type to password type.** Many developers can show other people the live stream but I think the key should not be visible. There can be sensitive data in outgoing telemetries.

**Comment by AlexBulankou** [comment]
@mholec  Thanks and agreed! Will fix this today and if you're using latest version, no Nuget package update should be necessary to pick up the changes.

**Comment by AlexBulankou** [comment]
This should be fixed now

**Comment by mirekholec** [comment]
Great, it works as expected ;)
